{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-25.11";
    nixpkgs-unstable.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    kernel-firecracker = {
      # Tree generated by this script:
      # https://github.com/firecracker-microvm/firecracker/pull/5637/commits/d043dc54b7326350b1c9b715cf784b06f5547d7f
      # (At that commit of the firecracker tree)
      # Then rebased onto a linux-next, with a couple of fixups and a new modparam.
      url = "github:bjackman/linux?ref=firecracker-host-2";
      flake = false;
    };
    kernel-firecracker-ephmap = {
      # Old version of the above, but with a simplistic ephmap call added to the
      # write path, with a simplistic TLB optimisation applied.
      url = "github:bjackman/linux?ref=firecracker-host+ephmap";
      flake = false;
    };
    kernel-benchmarks-nix = {
      # Using an experimental new version of this thing.
      url = "github:bjackman/kernel-benchmarks-nix?ref=v2";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{
      self,
      nixpkgs,
      nixpkgs-unstable,
      flake-utils,
      kernel-benchmarks-nix,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        formatter = pkgs.nixfmt-tree;

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [ nixos-rebuild ];
        };
      }
    )
    // flake-utils.lib.eachDefaultSystemPassThrough (system: {
      nixosConfigurations =
        let
          mkConfig =
            extraModules:
            nixpkgs.lib.nixosSystem {
              system = "x86_64-linux";
              modules = [
                ./modules/aethelred.nix
                kernel-benchmarks-nix.nixosModules.benchmarks.firecracker-perf-tests
                {
                  # Useful for poking around for experiments
                  nix.registry.nixpkgs-unstable.flake = nixpkgs-unstable;
                  nixpkgs.overlays = [ self.overlays.firecracker ];
                }
              ]
              ++ extraModules;
              specialArgs = { inherit self; };
            };
        in
        {
          base = mkConfig [ ];
          skip-flush = mkConfig [
            {
              boot.kernelParams = [ "kvm.guest_memfd_tlb_flush=0" ];
              system.nixos.variantName = "skip-flush";
            }
          ];
        };

      overlays.firecracker = (
        final: prev: {
          linuxPackages_firecracker = prev.linuxPackages_custom {
            version = "6.19.0-rc4-next-20260109";
            src = inputs.kernel-firecracker;
            # Use a massive config since that's the only thing I know makes Docker work.
            # This one has at least been through a make localmodconfig dance.
            configfile = ./kconfigs/v6.19_nix_big.config;
          };
          #  "populate_latency": [2056.114, 2060.27, 2040.085, 2060.202, 2075.324, 2033.987, 2057.317, 2035.927, 2058.438, 2056.828, 2061.481, 2031.189, 2029.544, 2040.335, 2032.227, 2041.634, 2041.136, 2061.472, 2066.608, 2053.442, 2038.645, 2062.134, 2036.871, 2062.678, 2056.329, 2057.52, 2056.166, 2056.378, 2061.378, 2063.784]}
          linuxPackages_firecracker-ephmap = prev.linuxPackages_custom {
            version = "6.17.0-rc3";
            src = inputs.kernel-firecracker-ephmap;
            # Use a massive config since that's the only thing I know makes Docker work.
            configfile = ./kconfigs/v6.17_nix_big.config;
          };
        }
      );
    });
}
